version: "3"
services:
  
  php:
    image: php:7.4-fpm
    container_name: php-sample-02
    volumes:
      - ./html:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    image: nginx:latest
    container_name: nginx-sample-02
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    restart: always
    ports: ["8080:80"]
    depends_on: ["php"]
